version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"

  php-redis-admin:
    image: faktiva/php-redis-admin
    environment:
        - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
        - "8080:80"
    depends_on:
        - redis

  redis-admin:
      image: marian/rebrow
      ports:
          - "5001:5001"
      depends_on:
          - redis
