version: "3.8"
services:
 mongo_db:
  image: mongo:latest
  ports:
   - 27018:27017
  environment:
   MONGO_INITDB_ROOT_USERNAME: admin
   MONGO_INITDB_ROOT_PASSWORD: password
   MONGO_INITDB_DATABASE: mongo
  networks:
   - awesome
  container_name: mongo_db
  volumes:
   - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
 web_app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: web_app
  ports:
    - 8080:8080
  networks:
   - awesome

networks:
 awesome: {}

volumes:
 awesome:
  driver: local